services:
  ##### build images (cpu, cuda, rocm) #################################################################################
  cpu-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: cpu
    image: its-cpu-build
    profiles: [ "cpu", "its-cpu" ]
  cuda-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: cuda
    image: its-cuda-build
    profiles: [ "cuda", "its-cuda" ]
  rocm-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: image
      args:
        src: rocm
    image: its-rocm-build
    profiles: [ "rocm", "its-rocm" ]
  ##### run ############################################################################################################
  its-cpu:
    image: its-cpu-build:latest
    depends_on:
      - cpu-build
    container_name: its-cpu
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target test_communication_nodes_rtsp -j 8 && communication/test_communication_nodes_rtsp"
    stop_signal: SIGTERM
    ports:
      - "8554:8554"
    profiles: [ "its-cpu" ]
  its-cuda:
    image: its-cuda-build:latest
    depends_on:
      - cuda-build
    container_name: its-cuda
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release -DCAFFE2_USE_CUDNN=True /src && cmake --build . --target its -j 8 && ./its"
    stop_signal: SIGTERM
    profiles: [ "its-cuda" ]
  its-rocm:
    image: its-rocm-build:latest
    depends_on:
      - rocm-build
    container_name: its-rocm
    volumes:
      - .:/src:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    command: sh -c "mkdir -p "/build" && cd "/build" && cmake -DCMAKE_BUILD_TYPE=Release /src && cmake --build . --target its -j 8 && ./its"
    stop_signal: SIGTERM
    profiles: [ "its-rocm" ]
  ##### MQTT ###########################################################################################################
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 1883:1883
      - 9001:9001
    network_mode: host
    profiles: [ "mqtt" ]
  ##### streaming server test ##########################################################################################
  streaming-server:
    # gst-launch-1.0 videotestsrc ! clockoverlay time-format="%D %H:%M:%S:%f" ! video/x-raw,width=640,height=480 ! videoconvert ! queue ! x264enc tune=zerolatency bitrate=1000 key-int-max=30 ! video/x-h264, profile=constrained-baseline ! rtph264pay pt=96 mtu=1200 ! udpsink host=127.0.0.1 port=1234
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: streaming_server
    network_mode: host
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - /etc/timezone:/etc/timezone:ro
    profiles: [ "streaming" ]
  streaming-server2:
    image: ghcr.io/voc/srtrelay/srtrelay:latest
    restart: always
    container_name: srtrelay
    volumes:
      - ./config.toml:/home/srtrelay/config.toml
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    profiles: [ "streaming2" ]